### ISSUE TITLE
Odd highlighting in floating windowns in nvim when you do a Hover

### ISSUE THREAD

**Issue by ckipp01** [neoclide/coc.nvim#1251]
## Result from CocInfo
```
vim version: NVIM v0.4.2
node version: v10.16.3
coc.nvim version: 0.0.74-a84f813105
term: iTerm.app
platform: darwin

## Output channel: tsserver

[Info  - 9:41:48 AM] Forking TSServer
PATH: /<my path stuff>
[Info  - 9:41:48 AM] Started TSServer

{
  "path": "/Users/me/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.6.2",
    "version": "3.6.2"
  }
}
```

## Describe the bug

When I issue a `call CocAction('doHover')` the highlighting that is found on the parens around (method) are highlighted in a way that makes it really hard to see depending on your theme. I've noticed this highlighting with nvim's floating window in a way that doesn't really seem to add anything or make sense. Is there a way to turn it off?

## Reproduce the bug

You can reproduce this using the mini.vim that you have listed below.

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

Open up the following js file:
```javascript
const someFunction = (result) => {
  console.info(JSON.parse(result))
}
```

do a call CocAction('doHover')` on parse or any other function and you'll see something that exists like below in the screenshots.

## Screenshots (optional)

Example with the mini.vim being used as a vimrc. Notice the highlighting around the (method)...
<img width="267" alt="Screenshot 2019-10-09 at 09 28 02" src="https://user-images.githubusercontent.com/13974112/66461447-5769ba80-ea79-11e9-9162-e57a2d969c6c.png">

A couple other snapshots with a theme to elaborate on what I mean about how it can completely throw off the way it looks. The first example is JS and the second is Scala

<img width="326" alt="Screenshot 2019-10-08 at 14 13 20" src="https://user-images.githubusercontent.com/13974112/66461528-82eca500-ea79-11e9-9f72-2a5bfaee2565.png">

<img width="497" alt="Screenshot 2019-10-08 at 14 13 41" src="https://user-images.githubusercontent.com/13974112/66461534-85e79580-ea79-11e9-9625-7d484226b6f0.png">

## Recap

I can't figure out why the () in the floating windows are being highlighted, and seemingly at times also what is between ` : ` in a type signature. How do I either turn this off or what is actually causing this?

**Comment by chemzqm** [comment]
No idea, try disable your syntax plugins to see which one causing this problem.

**Comment by ckipp01** [comment]
The first image I posted has no plugins enabled. It's only with loading the mini.vim file that you gave as an example.

**Comment by ckipp01** [comment]
Thanks for the quick fix!

Just in case someone else stumbles here. I have been playing around with this for a while not to figure out what's happening. While the fix pushed indeed fixes it on a vanilla nvim with no theme, when a theme is added *and*  you have `set termguicolors` you will still see the odd highlighting. However, if you turn it off, then the odd highlighting goes away. I'm not fully sure why that changes the highlighting in the floating windows, but it does.

**Comment by chemzqm** [comment]
Don't know, the nvim used for highlight use `--norc` argument.

**Comment by ckipp01** [comment]
Is there a chance you'd be willing to chime in on this? https://github.com/dracula/vim/issues/155

I've consistently seen this across a lot of themes that show an odd highlighting in the hover window

![image](https://user-images.githubusercontent.com/13974112/69569244-87373800-0fbd-11ea-839c-82ef8d208c43.png)

I originally thought this was solved some time ago, but it keeps popping up.

**Comment by oblitum** [comment]
Can confirm this is still an issue:

![img-2021-11-16-234109](https://user-images.githubusercontent.com/1269815/142113056-6bb9c215-d0dc-4f9d-a43f-06eeaf9b6a55.png)

Parenthesis in signatureHelp get a darker background than float window. Floating window background links to Pmenu, the parenthesis seem to be associated with Normal text, doing `:hi! link Normal Pmenu` force the issue to vanish.

**Comment by fannheyward** [comment]
@oblitum what's the color scheme do you use? I'm using `dracula`:

 <img width="724" alt="截屏2021-11-17 上午11 57 47" src="https://user-images.githubusercontent.com/345274/142132018-9e3c072b-474d-414e-8e11-ea7f2e38f408.png">

**Comment by oblitum** [comment]
[zenbones](https://github.com/mcchrish/zenbones.nvim), neobones variant, which makes the issue more explicit. The other one I posted earlier also had it, but not so contrasting, it was [rosepine](https://github.com/rose-pine/neovim).

Using the mouse to enter the float, I can play around with `:hi Normal`, etc, and this feels like some bug with NeoVim's `&winhl` feature as used by coc's `float.vim`. Changing Normal from inside float, I change the parens background and main normal, but not floats background.

**Comment by oblitum** [comment]
This spot in coc.nvim own source code makes for a good test of broken highlighting:

![img-2021-11-23-203420](https://user-images.githubusercontent.com/1269815/143145513-27939030-3518-4894-8a9f-3914ca75f73e.png)

You can not only not the parentheses still present the same issue as before, but there's an additional issue. you can see that in the highlighting of the signature, in the three top lines, the first line has a white on black `(` and a red `{`, these are closed in the 3rd line, but they don't match the colors of the opening ones, they're just normal text, possibly because it's not all in the same line, and whatever this custom syntax highlighting is doing, it can't work on multiple lines at the moment it seems.

(rosepine was used)

**Comment by oblitum** [comment]
@fannheyward in case you can reproduce, could you please reopen this?

**Comment by fannheyward** [comment]
<img width="882" alt="截屏2021-11-24 上午9 03 06" src="https://user-images.githubusercontent.com/345274/143152601-51d11467-ed4a-4e11-b522-acde1b8f775e.png">

@oblitum I can't reproduce this... it's really hard/difficult  to to do highlighting...

**Comment by oblitum** [comment]
@fannheyward I advice trying with any of those two colorschemes I mentioned, it may not be apparent in others.

**Comment by fannheyward** [comment]
Reproduced with https://github.com/rose-pine/neovim

**Comment by oblitum** [comment]
FWIW, I have disabled tree-sitter for typescript, and coc semantic tokens, just to make it more simple to analyzer, and those light red colored braces come from colorscheme, it didn't show in the previous screenshot because tree-sitter has overrode that in the colorscheme, but float still kept it because there's no tree-sitter in floats.

**Comment by oblitum** [comment]
This is the cause:

- https://github.com/neovim/neovim/issues/16419

Related lines are:

- [autoload/coc/highlight.vim#L314](https://github.com/neoclide/coc.nvim/blob/78cddd99a5f2f462d1cf375983517e8bf0f6b9aa/autoload/coc/highlight.vim#L314)
- [autoload/coc/float.vim#L150](https://github.com/neoclide/coc.nvim/blob/78cddd99a5f2f462d1cf375983517e8bf0f6b9aa/autoload/coc/float.vim#L150)

**Comment by oblitum** [comment]
That's not the cause for the other issue regarding non balanced brace colors though, just the former one.

**Comment by oblitum** [comment]
I think coc.nvim needs to remove any usage of `winhighlight` from its source code and look for an alternative, as the NeoVim-only feature has inconsistent behavior, and a fix to https://github.com/neovim/neovim/issues/16419 will arrive, if it ever comes, only in some future version. It also may get lower priority as it's being tagged as feature request instead of bug.

**Comment by oblitum** [comment]
As usual, nvim devs finished playing their deflecting game, locked the issue, without bothering to have their docs a bit clearer, because it's everything obvious already, despite the user experience here and elsewhere.

**Comment by oblitum** [comment]
After research in #3487, this leans towards a wontfix (as there's no way to fix?), at least for now.

**Comment by chemzqm** [comment]
Remove/override `typescriptParens` highlight group or wait until we could use something like treesister for highlights instead of vim's syntax highlighting.
