### ISSUE TITLE
Output to quickfix list

### ISSUE THREAD

**Issue by matthewgrossman** [neoclide/coc.nvim#480]
**Describe the solution you'd like**
The list described in https://github.com/neoclide/coc.nvim/issues/347 is awesome in certain situations and allows for quick filtering for many list-based action. 

However, sometimes I wish I could dump all of the searched results to a [vim quickfix window](http://vimdoc.sourceforge.net/htmldoc/quickfix.html) instead. There are already a bunch of plugins and knowledge around quickfix windows (`:cdo`, `romainl/vim-qf`, `tpope/vim-unimpaired`, etc). Depending on what I'm doing, I wish I could just deal with the interface I know instead of a new bespoke coc-list.

Can we make an option for location commands to output results into a quickfix list instead of the [coc-list](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L1036url)?

**Comment by chemzqm** [comment]
It's possible to use quickfix instead of CocList, could you tell me what features you need for quickfix list?

**Comment by shyun3** [comment]
+1. While using ccls I find that the outputs of commands such as <Plug>(coc-references) and :call CocLocations('ccls','$ccls/call')<cr> would be more appropriate in the quickfix list. 

When you're interested in only one entry in a list, like for a particular symbol in the current document, the coc-list is more convenient to navigate through. But when you may be interested in all the entries in a list like for all callers of a function, I think it would be better to use the quickfix list.

**Comment by chemzqm** [comment]
> I think it would be better to use the quickfix list.

Why? Could you explain?
It's designed to not use quickfix because it's possible you have a background linter or compiler that populate errors to quickfix.

**Comment by shyun3** [comment]
Well maybe it shouldn't by default but I think the OP's point is that having an option would be most flexible for the users because they can then use things like `:cdo`.

**Comment by matthewgrossman** [comment]
@shyun3 had the exact example I was thinking of:  `<Plug>(coc-references)`. Often I'm looking to do some bulk operations on my references rather than trying to drill down into a specific reference.

I do agree that many different plugins populate the quickfix list, but I think that's a problem that can only be solved with user-level configuration. I have `ale` populating my location list (configuration) instead of quickfix list, [for example](https://github.com/w0rp/ale#faq-quickfix). A ton of plugins (and builtins) use the quickfix list, so IMO I wouldn't worry too much about intruding into the quickfix list (assuming you allow for configuration)

**Comment by chemzqm** [comment]
I've add `coc.preferences.useQuickfixForLocations` settings support to master.
There is plan to make the locations list source editable, so you can just edit and save for code refactor.

**Comment by shyun3** [comment]
I updated to the latest commit and added the line:
```
"coc.preferences.useQuickfixForLocations": true,
```
to my coc config but my location commands still use the coc lists.

**Comment by chemzqm** [comment]
@shyun3 make sure you don't have `{'tag':'*'}` in your plug command of coc.nvim if you want to use master code.

**Comment by shyun3** [comment]
Ok, the git log now says:
```
commit afd005eb6a9cef1ab29f9024c4c13f1c325bc359 (HEAD -> master, origin/master, origin/HEAD)
Author: chemzqm <chemzqm@gmail.com>
Date:   Mon Mar 4 16:15:22 2019 +0800

    feat(settings): add `coc.preferences.useQuickfixForLocations`
```
but when I use `<Plug>(coc-references)` or `:call CocLocations('ccls','$ccls/call')` the quickfix list is still not populated. The only coc related settings in my init.vim are mappings and the airline customizations.

**Comment by chemzqm** [comment]
Did you build the code by run `yarn install` in plugin root?

**Comment by shyun3** [comment]
Ok, looks like it's working now. Sorry, I thought that the `{'do': { -> coc#util#install()}}` would run through all the necessary install steps.

**Comment by nhooyr** [comment]
Thank you for this! I much prefer it in my quick fix list as I already have bindings for it and it stays open so I can go through references one by one in my main window.

**Comment by chemzqm** [comment]
>  so I can go through references one by one in my main window.

You can use `:CocPrev` and `:CocNext` as well.

**Comment by nhooyr** [comment]
The quick fix window shows me the list constantly though so I know what the next item will be whereas with `CocNext` it feels jarring.

**Comment by chemzqm** [comment]
I prefer not keep the list open since I can have more lines for main window, and there is CocResume command to reopen the list.

**Comment by williamboman-pp** [comment]
> CocResume command to reopen the list.

I don't seem to have this, is this not in `master` yet?

**Comment by chemzqm** [comment]
It's created on coc.nvim load

**Comment by GrantJamesPowell** [comment]
This is in the current release right? I'm trying to use `quickfix` for coc locations and it seems to be falling back to the `CocList` and not quickfix

relevant  `~/.config/nvim/coc-settings.json`
```
  "coc": {
    "preferences": {
      "useQuickfixForLocations": true
    }
  },
```
```
## versions

vim version: NVIM v0.5.1
node version: v17.1.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/grantpowell/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

**Comment by fnune** [comment]
The contents of previous quickfix lists aren't lost: you can recover them with `:colder` and go forward again with `:cnewer`.

```
:h :colder
```

```
So far has been assumed that there is only one list of errors.  Actually the
ten last used lists are remembered.  When starting a new list, the previous
ones are automatically kept.  Two commands can be used to access older error
lists.  They set one of the existing error lists as the current one.
```

**Comment by dmitry-markin** [comment]
I am trying to make use of `"coc.preferences.useQuickfixForLocations": true` in `coc-settings.json` by directing plug to the master branch:
```
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'npm i'}
```
or the same in lua:
```
Plug('neoclide/coc.nvim', {branch = 'master', ['do'] = 'npm i'})
```
but `:CocDiagnostics` still opens the location list. What am I doing wrong?

**Comment by chemzqm** [comment]
> I am trying to make use of `"coc.preferences.useQuickfixForLocations": true` in `coc-settings.json` by directing plug to the master branch:
> 
> ```
> Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'npm i'}
> ```
> 
> or the same in lua:
> 
> ```
> Plug('neoclide/coc.nvim', {branch = 'master', ['do'] = 'npm i'})
> ```
> 
> but `:CocDiagnostics` still opens the location list. What am I doing wrong?
> 
> EDIT: `:CocList diagnostics` does not open the quickfix list either. Instead it opens a list with `FUZZY >` prompt that is instantly closed once any location is selected.

That setting works for locations list only, `:CocList diagnostics` uses location list.
You'll need to use API `CocAction('diagnosticList')` to get list of all diagnostics and fill them to quickfix list.
